### ISSUE TITLE
Add Japanese translations

### ISSUE THREAD

**Issue by nidegen** [nidegen/Localizer#9]

**Comment by MozyOk** [comment]
Hi @nidegen 👋
I'll try to add japanese support, ok?

**Comment by nidegen** [comment]
sure. you dont have to translate all existings. on the other side you are welcome to also add additional words:)

**Comment by nidegen** [comment]
@MozyOk make sure to update from master, i just moved a few files around

**Comment by MozyOk** [comment]
Hi @nidegen 👋
please check. 🙏
https://github.com/nidegen/Localizer/pull/14

**Comment by nidegen** [comment]
thanks
